### ISSUE TITLE
As Timeseries: make it work with sparse matrices

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-timeseries#106]
##### Timeseries version

0.3.6

##### Orange version

3.26.0.dev

##### Expected behavior
As Timeseries can work with sparse matrices.

##### Actual behavior
As Timeseries crashes.

##### Steps to reproduce the behavior
Corpus - Bag of Words - As Timeseries.

##### Additional info (worksheets, data, screenshots, ...)

From attribute:
```
-------------------------- AttributeError Exception ---------------------------
Traceback (most recent call last):
  File "/Users/ajda/orange/orange-canvas-core/orangecanvas/scheme/signalmanager.py", line 936, in __process_next
    if self.__process_next_helper(use_max_active=True):
  File "/Users/ajda/orange/orange-canvas-core/orangecanvas/scheme/signalmanager.py", line 974, in __process_next_helper
    self.process_node(selected_node)
  File "/Users/ajda/orange/orange-canvas-core/orangecanvas/scheme/signalmanager.py", line 605, in process_node
    self.send_to_node(node, signals_in)
  File "/Users/ajda/orange/orange-widget-base/orangewidget/workflow/widgetsscheme.py", line 792, in send_to_node
    self.process_signals_for_widget(node, widget, signals)
  File "/Users/ajda/orange/orange-widget-base/orangewidget/workflow/widgetsscheme.py", line 826, in process_signals_for_widget
    handler(*args)
  File "/Users/ajda/orange/orange3-timeseries/orangecontrib/timeseries/widgets/owtabletotimeseries.py", line 75, in set_data
    self.on_changed()
  File "/Users/ajda/orange/orange3-timeseries/orangecontrib/timeseries/widgets/owtabletotimeseries.py", line 78, in on_changed
    self.commit()
  File "/Users/ajda/orange/orange-widget-base/orangewidget/gui.py", line 1586, in unconditional_commit
    do_commit()
  File "/Users/ajda/orange/orange-widget-base/orangewidget/gui.py", line 1594, in do_commit
    commit()
  File "/Users/ajda/orange/orange3-timeseries/orangecontrib/timeseries/widgets/owtabletotimeseries.py", line 94, in commit
    values = Table.from_table(Domain([], [], [time_var]),
  File "/Users/ajda/opt/miniconda3/envs/o3/lib/python3.8/site-packages/scipy/sparse/base.py", line 691, in __getattr__
    raise AttributeError(attr + " not found")
AttributeError: ravel not found
```

From sequence:
```
---------------------------- ValueError Exception -----------------------------
Traceback (most recent call last):
  File "/Users/ajda/orange/orange-widget-base/orangewidget/gui.py", line 1810, in __call__
    self.func(**kwds)
  File "/Users/ajda/orange/orange3-timeseries/orangecontrib/timeseries/widgets/owtabletotimeseries.py", line 78, in on_changed
    self.commit()
  File "/Users/ajda/orange/orange-widget-base/orangewidget/gui.py", line 1586, in unconditional_commit
    do_commit()
  File "/Users/ajda/orange/orange-widget-base/orangewidget/gui.py", line 1594, in do_commit
    commit()
  File "/Users/ajda/orange/orange3-timeseries/orangecontrib/timeseries/widgets/owtabletotimeseries.py", line 88, in commit
    ts = Timeseries.make_timeseries_from_sequence(data)
  File "/Users/ajda/orange/orange3-timeseries/orangecontrib/timeseries/timeseries.py", line 169, in make_timeseries_from_sequence
    X = np.column_stack((np.arange(1, len(table) + 1), X))
  File "<__array_function__ internals>", line 5, in column_stack
  File "/Users/ajda/opt/miniconda3/envs/o3/lib/python3.8/site-packages/numpy/lib/shape_base.py", line 656, in column_stack
    return _nx.concatenate(arrays, 1)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 463 and the array at index 1 has size 1
-------------------------------------------------------------------------------
```

**Comment by ajdapretnar** [comment]
For the record, I also couldn't reproduce the "From sequence" bug.
