### ISSUE TITLE
Line Chart not working?

### ISSUE THREAD

**Issue by ajhayes83** [biolab/orange3-timeseries#11]
[Orange version 3.4.1, same in earlier versions I've tried too]

Expect to get line graph plotted by 'Line Chart' when inputing time series data from 'As Timeseries' into 'Line Chart' (in 'Time Series' add-on)

On opening Line Chart, I see my two column headings 'temperature' and 'activity' inside the left hand side box under the 'Logarithmic axis', but I get a large empty box on the right hand side where I would expect a plot. Can you help? Is this just me or is there a problem with 'Line Chart'?

Many thanks for help!

**Comment by kernc** [comment]
What version of add on is this?

**Comment by ajhayes83** [comment]
Thanks. This is Time Series v0.2.7 on Orange v3.4.1.

**Comment by kernc** [comment]
Can you attach the output of `python3 -m Orange.canvas -l 4` as run from the command line? Note, `python3` must be from the same environment where Orange is installed. What OS is this?

**Comment by ajhayes83** [comment]
Thanks v much.

lf-mac-0250:~ alastairhayes$ python3 -m Orange.canvas -l 4
/Library/Frameworks/Python.framework/Versions/3.5/bin/python3: Error while finding spec for 'Orange.canvas' (<class 'ImportError'>: No module named 'Orange')

Do you thinks this could be the problem - is there a way to work around this?

Background: In Anaconda Navigator, I use 'orange3' environment which was created when I tried to install orange3 in 'py3k' environment as py3k returned comment that 'orange3 cannot be installed on this environment'. I'm unclear why that is the case and maybe if I could install in py3k, I wouldn't be having this issue...?!

My MacBook pro is macOS Sierra v10.12.3.
Thanks.

**Comment by kernc** [comment]
Hmm.. I don't know. But I'm certain you aren't using the correct python3 executable. Where is Anaconda installed? In Anaconda's distribution there should be a python in the _bin_ folder (e.g. `~/anaconda/bin/python`). Or open Anaconda terminal console, and use the `python` executable as available within.

**Comment by ajhayes83** [comment]
Thanks. 
Anaconda is in 'Macintosh HD' folder.
I find anaconda/bin/python2.7 (but no python3)
Could I request anaconda update to python 3 somehow using the command line - would that help?

**Comment by kernc** [comment]
> On opening Line Chart, I see my two column headings 'temperature' and 'activity' inside the left hand side box under the 'Logarithmic axis', but I get a large empty box on the right hand side where I would expect a plot.

Can you share a screenshot? Either 'temperature' or 'activity' (or both) needs to be selected in order to plot the line.

**Comment by ajhayes83** [comment]
<img width="1680" alt="line chart not working" src="https://cloud.githubusercontent.com/assets/10696257/24157544/8b37e0dc-0e51-11e7-9088-6e01b1bf49c6.png">

**Comment by ajhayes83** [comment]
<img width="1680" alt="distributions is working" src="https://cloud.githubusercontent.com/assets/10696257/24157783/47bd5386-0e52-11e7-86aa-7785e1279214.png">

**Comment by ajhayes83** [comment]
You can see selected data out from data table is ok - works in 'distributions' visualisation

**Comment by kernc** [comment]
Right. So provided you installed Anaconda in the proposed default directory, can you please run:
```bash
~/anaconda3/bin/python -m Orange.canvas --log-level=4
```
and paste the output of the session where Line Chart is used. Thanks.

**Comment by ajhayes83** [comment]
Many thanks for your help. I tried ~/anaconda3/bin/python -m Orange.canvas --log-level=4
and this returned: No such file or directory. I guess it must be issue with my anaconda installation and python versions.Also I was having little joy with anaconda-navigator and this seemed to be complicating things for me so instead went for the simple option and installed the bundle for mac from orange.biolab.si webpage (v3.4.1.).
This is now working well and Line Chart is working in time series add on - problem solved.
Thanks for your help and patience.
<img width="1680" alt="line chart working" src="https://cloud.githubusercontent.com/assets/10696257/24396125/0717a5be-139a-11e7-92d7-965f9e7adf3f.png">

**Comment by alum** [comment]
I am running into this problem too. I've tried with the 3.14 version MacOS bundle as well as a `pip` installed version which says it's 3.15.

Running Orange with `python3 -m Orange.canvas --log-level=4` gives me the following error when I click the "Count" column name in the line chart widget:

```js: Uncaught Error: Highcharts error #18: www.highcharts.com/errors/18```

My setup:
<img width="1048" alt="screen shot 2018-08-07 at 16 48 10" src="https://user-images.githubusercontent.com/122738/43783431-047a0e82-9a62-11e8-83fb-a0ff568eb40a.png">
<img width="1068" alt="screen shot 2018-08-07 at 16 48 13" src="https://user-images.githubusercontent.com/122738/43783430-045d907c-9a62-11e8-8779-7b6aee4cf703.png">

The .tsv file I load:

```
Timestamp	Count
t	c
	
2018-03-07T12:00:00+0100	10.0
2018-03-07T13:00:00+0100	12.0
2018-03-07T14:00:00+0100	0.0
2018-03-07T15:00:00+0100	0.0
2018-03-07T16:00:00+0100	0.0
2018-03-07T17:00:00+0100	0.0
2018-03-07T18:00:00+0100	0.0
2018-03-07T19:00:00+0100	0.0
2018-03-07T20:00:00+0100	0.0
2018-03-07T21:00:00+0100	0.0
2018-03-07T22:00:00+0100	0.0
2018-03-07T23:00:00+0100	0.0
2018-03-08T00:00:00+0100	30.0
2018-03-08T01:00:00+0100	50.0
2018-03-08T02:00:00+0100	110.0
2018-03-08T03:00:00+0100	210.0
2018-03-08T04:00:00+0100	320.0
2018-03-08T05:00:00+0100	230.0
2018-03-08T06:00:00+0100	20.0
2018-03-08T07:00:00+0100	20.0
2018-03-08T08:00:00+0100	0.0
2018-03-08T09:00:00+0100	0.0
2018-03-08T10:00:00+0100	10.0
2018-03-08T11:00:00+0100	4.0
2018-03-08T12:00:00+0100	12.0
```

Full log of the session:

```
$ python3 -m Orange.canvas --log-level=4
/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Setting up Canvas main window.
'CanvasScene(objectName='', ...)' intitialized.
Setting registry 'None on 'CanvasScene(objectName='', ...)'.
Scheme node properties sync (changed: False)
'CanvasScene(objectName='', ...)' cleared.
'CanvasScene(objectName='', ...)' intitialized.
Setting registry 'None on 'CanvasScene(objectName='', ...)'.
Setting scheme '<Orange.canvas.scheme.widgetsscheme.WidgetsScheme object at 0x12836bdc8>' on 'CanvasScene(objectName='', ...)'
Stack transition start ()
Stack transition finished ()
Dock transition finished (new width 640)
Dock transition started.
Loading widget registry cache ('/Users/filip/Library/Caches/Orange/3.15.0/canvas/registry-cache.pck').
Ignoring '/usr/local/lib/python3.6/site-packages/Orange/widgets/data/contexthandlers.py'.
Ignoring '/usr/local/lib/python3.6/site-packages/Orange/widgets/visualize/owscatterplotgraph.py'.
Ignoring '/usr/local/lib/python3.6/site-packages/Orange/widgets/visualize/owtreeviewer2d.py'.
Ignoring '/usr/local/lib/python3.6/site-packages/Orange/widgets/visualize/pythagorastreeviewer.py'.
Ignoring '/usr/local/lib/python3.6/site-packages/Orange/widgets/evaluate/contexthandlers.py'.
Ignoring '/usr/local/lib/python3.6/site-packages/Orange/widgets/evaluate/utils.py'.
/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Ignoring '/usr/local/lib/python3.6/site-packages/orangecontrib/timeseries/widgets/_owmodel.py'.
Ignoring '/usr/local/lib/python3.6/site-packages/orangecontrib/timeseries/widgets/_rangeslider.py'.
Error while importing 'orangecontrib.timeseries.widgets.owyahoofinance'. The widget will not be shown.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/Orange/canvas/registry/discovery.py", line 261, in iter_widget_descriptions
    module = asmodule(name)
  File "/usr/local/lib/python3.6/site-packages/Orange/canvas/registry/discovery.py", line 491, in asmodule
    return __import__(module, fromlist=[""])
  File "/usr/local/lib/python3.6/site-packages/orangecontrib/timeseries/widgets/owyahoofinance.py", line 10, in <module>
    from orangecontrib.timeseries.datasources import finance_data
  File "/usr/local/lib/python3.6/site-packages/orangecontrib/timeseries/datasources.py", line 4, in <module>
    import pandas_datareader.data as web
  File "/usr/local/lib/python3.6/site-packages/pandas_datareader/__init__.py", line 2, in <module>
    from .data import (DataReader, Options, get_components_yahoo,
  File "/usr/local/lib/python3.6/site-packages/pandas_datareader/data.py", line 14, in <module>
    from pandas_datareader.fred import FredReader
  File "/usr/local/lib/python3.6/site-packages/pandas_datareader/fred.py", line 1, in <module>
    from pandas.core.common import is_list_like
ImportError: cannot import name 'is_list_like'
Ignoring '/usr/local/lib/python3.6/site-packages/orangecontrib/timeseries/widgets/utils.py'.
Saving widget registry cache with 101 entries ('/Users/filip/Library/Caches/Orange/3.15.0/canvas/registry-cache.pck').
'set_global_registry()' - setting registry.
Setting registry '<Orange.canvas.registry.qt.QtWidgetRegistry object at 0x12d5e4a68> on 'CanvasScene(objectName='', ...)'.
Invalid replacement fields {'DEVELOP_ROOT'}
Created <class 'Orange.canvas.help.provider.HtmlIndexProvider'> provider for Orange3 3.15.0
Invalid replacement fields {'DEVELOP_ROOT'}
Created <class 'Orange.canvas.help.provider.HtmlIndexProvider'> provider for Orange3-Timeseries 0.3.3
objc[82494]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffad527c90) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1392cbcd8). One of the two will be used. Which one is undefined.
Added node 'File' to scheme ''.
Added node 'As Timeseries' to scheme ''.
Added node 'Line Chart' to scheme ''.
Added link 'File' ('Data') -> 'As Timeseries' ('Data') to scheme ''.
Link added (SchemeLink((File, Data) -> (As Timeseries, Data))). Scheduling signal data update.
Added link 'As Timeseries' ('Time series') -> 'Line Chart' ('Time series') to scheme ''.
Link added (SchemeLink((As Timeseries, Time series) -> (Line Chart, Time series))). Scheduling signal data update.
Scheme node properties sync (changed: False)
'CanvasScene(objectName='', ...)' cleared.
'CanvasScene(objectName='', ...)' intitialized.
Setting registry '<Orange.canvas.registry.qt.QtWidgetRegistry object at 0x12d5e4a68> on 'CanvasScene(objectName='', ...)'.
Setting scheme '<Orange.canvas.scheme.widgetsscheme.WidgetsScheme object at 0x133929e58>' on 'CanvasScene(objectName='', ...)'
Added item '<Orange.canvas.canvas.items.nodeitem.NodeItem object at 0x12ea28708>' to 'CanvasScene(objectName='', ...)'
Added item '<Orange.canvas.canvas.items.nodeitem.NodeItem object at 0x139e5e048>' to 'CanvasScene(objectName='', ...)'
Added item '<Orange.canvas.canvas.items.nodeitem.NodeItem object at 0x139e5eaf8>' to 'CanvasScene(objectName='', ...)'
Added link 'File' -> 'As Timeseries' to 'CanvasScene(objectName='', ...)'
Added link 'As Timeseries' -> 'Line Chart' to 'CanvasScene(objectName='', ...)'
WidgetManager: Creating 'Orange.widgets.data.owfile.OWFile' instance 'File'.
'UpdateRequest' event, queued signals: 0, nbusy: 2 (MAX_CONCURRENT: 1)
Pending nodes: []
Blocking nodes: {SchemeNode(description_id=orangecontrib.timeseries.widgets.owlinechart, title='Line Chart', ...), SchemeNode(description_id=orangecontrib.timeseries.widgets.owtabletotimeseries, title='As Timeseries', ...)}
WidgetManager: Creating 'orangecontrib.timeseries.widgets.owtabletotimeseries.OWTableToTimeseries' instance 'As Timeseries'.
WidgetManager: Creating 'orangecontrib.timeseries.widgets.owlinechart.OWLineChart' instance 'Line Chart'.
'File' sending <class 'Orange.data.table.Table'> (id: (1, 'Data', None)) on channel 'Data'
'UpdateRequest' event, queued signals: 1, nbusy: 1 (MAX_CONCURRENT: 1)
Pending nodes: [SchemeNode(description_id=orangecontrib.timeseries.widgets.owtabletotimeseries, title='As Timeseries', ...)]
Blocking nodes: {SchemeNode(description_id=orangecontrib.timeseries.widgets.owlinechart, title='Line Chart', ...)}
'UpdateRequest' event, queued signals: 1, nbusy: 0 (MAX_CONCURRENT: 1)
SignalManager: Processing queued signals
Pending nodes: [SchemeNode(description_id=orangecontrib.timeseries.widgets.owtabletotimeseries, title='As Timeseries', ...)]
Blocking nodes: set()
SignalManager: Nodes eligible for update ['As Timeseries']
Processing 'As Timeseries', sending 1 signals.
Process signals: calling OWTableToTimeseries.set_data (from SchemeLink((File, Data) -> (As Timeseries, Data)) with id:(1, 'Data', None))
'As Timeseries' sending <class 'orangecontrib.timeseries.timeseries.Timeseries'> (id: (2, 'Time series', None)) on channel 'Time series'
Pending nodes: [SchemeNode(description_id=orangecontrib.timeseries.widgets.owlinechart, title='Line Chart', ...)]
Blocking nodes: set()
More nodes are eligible for an update. Scheduling another update.
'UpdateRequest' event, queued signals: 1, nbusy: 0 (MAX_CONCURRENT: 1)
SignalManager: Processing queued signals
Pending nodes: [SchemeNode(description_id=orangecontrib.timeseries.widgets.owlinechart, title='Line Chart', ...)]
Blocking nodes: set()
SignalManager: Nodes eligible for update ['Line Chart']
Processing 'Line Chart', sending 1 signals.
Process signals: calling OWLineChart.set_data (from SchemeLink((As Timeseries, Time series) -> (Line Chart, Time series)) with id:(2, 'Time series', None))
Pending nodes: []
Blocking nodes: set()
js: Uncaught Error: Highcharts error #18: www.highcharts.com/errors/18
```

Obviously there are a few other warnings/errors that I have no idea if they affect the time series line chart widget.

**Comment by ajdapretnar** [comment]
I would close this as a stale issue and since it worked with the official installer. Also, Anaconda distribution requires setting the correct channel. Please see installation instructions for details.

Also, reopen if the problem persists with the current version.

For other issues regarding Timeseries, please open a new issue.
