### ISSUE TITLE
Time Slice: Looping on different data causes error

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-timeseries#132]
##### Timeseries version

master

##### Orange version

3.27.dev

##### Expected behavior
Looping is error-free.

##### Actual behavior
When changing a data set while looping in Time Slice, the following error occurs.

```
Traceback (most recent call last):
  File "/home/travis/build/biolab/orange3-timeseries/orangecontrib/timeseries/widgets/tests/test_owdifference.py", line 17, in setUp
    self.data = Timeseries.from_url(url)
  File "/home/travis/build/biolab/orange3-timeseries/orangecontrib/timeseries/timeseries.py", line 165, in from_url
    return cls.from_data_table(table)
  File "/home/travis/build/biolab/orange3-timeseries/orangecontrib/timeseries/timeseries.py", line 128, in from_data_table
    ts.time_variable = time_variable
  File "/home/travis/build/biolab/orange3-timeseries/orangecontrib/timeseries/timeseries.py", line 221, in time_variable
    self.time_delta = TimeDelta(self.time_values)
  File "/home/travis/build/biolab/orange3-timeseries/orangecontrib/timeseries/timeseries.py", line 61, in __init__
    self.gcd = int(np.gcd.reduce(nds + list(self._SPAN_DAY)))
TypeError: No loop matching the specified signature and casting was found for ufunc gcd
```

##### Steps to reproduce the behavior
Datasets (select a data set with time var) - As Timeseries - Time Slice. Loop through. Change the data set while looping.

**Comment by irgolic** [comment]
Can't reproduce on master. Which data sets?
