### ISSUE TITLE
Line Chart: ZeroDivisionError

### ISSUE THREAD

**Issue by scrollinondubs** [biolab/orange3-timeseries#171]
##### Timeseries version
0.3.10

##### Orange version
3.29.3  

##### Expected behavior
Line Chart should display the data.

##### Actual behavior
Line Chart throws a division by zero error and shows no data. 

##### Steps to reproduce the behavior
Drag Line Chart component onto canvas and connect to any dataset. 

##### Additional info (worksheets, data, screenshots, ...)
This Loom reproduces what I'm seeing: https://www.loom.com/share/fffd86e8577f4e238e1c4ca5c13ac2a6
And here's the stacktrace of that error that comes up:

```
------------------------- ZeroDivisionError Exception -------------------------
Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecanvas/scheme/signalmanager.py", line 1024, in __process_next
    if self.__process_next_helper(use_max_active=True):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecanvas/scheme/signalmanager.py", line 1062, in __process_next_helper
    self.process_node(selected_node)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecanvas/scheme/signalmanager.py", line 690, in process_node
    self.send_to_node(node, signals_in)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangewidget/workflow/widgetsscheme.py", line 806, in send_to_node
    self.process_signals_for_widget(node, widget, signals)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangewidget/workflow/widgetsscheme.py", line 820, in process_signals_for_widget
    process_signals_for_widget(widget, signals, workflow)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangewidget/workflow/widgetsscheme.py", line 921, in process_signals_for_widget
    process_signal_input(input_meta, widget, signal, workflow)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangewidget/workflow/widgetsscheme.py", line 884, in process_signal_input_default
    notify_input_helper(
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangewidget/utils/signals.py", line 639, in set_input_helper
    handler(*args)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangewidget/utils/signals.py", line 197, in summarize_wrapper
    method(widget, value)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/timeseries/widgets/owlinechart.py", line 531, in set_data
    self.set_attributes()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/timeseries/widgets/owlinechart.py", line 599, in set_attributes
    self.openContext(self.data.domain)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangewidget/widget.py", line 1109, in openContext
    self.settingsHandler.open_context(self, *a)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Orange/widgets/settings.py", line 125, in open_context
    super().open_context(widget, domain, *self.encode_domain(domain))
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangewidget/settings.py", line 823, in open_context
    self.find_or_create_context(widget, *args)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangewidget/settings.py", line 855, in find_or_create_context
    best_context, best_score = self.find_context(self.global_contexts, args,
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangewidget/settings.py", line 875, in find_context
    score = self.match(context, *args)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/timeseries/widgets/owlinechart.py", line 439, in match
    return sum(all_vars.get(attr) == vtype for attr, vtype in value) / len(
ZeroDivisionError: division by zero
-------------------------------------------------------------------------------
--------------------------- TimeoutError Exception ----------------------------
Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangewidget/utils/webview.py", line 369, in _later
    self._evalJS(code)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangewidget/utils/webview.py", line 575, in _evalJS
    wait(until=lambda: result in self._results,
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangewidget/utils/webview.py", line 418, in wait
    raise TimeoutError()
TimeoutError
-------------------------------------------------------------------------------

```

**Comment by cerrodragon** [comment]
I have the same issue.

**Comment by cerrodragon** [comment]
Did you solve it?

**Comment by PrimozGodec** [comment]
It is solved https://github.com/biolab/orange3-timeseries/pull/167. If the issue still appears please reopen the issue.
