### ISSUE TITLE
ARIMA and VAR blocks not showing dialog

### ISSUE THREAD

**Issue by dwolf33** [biolab/orange3-timeseries#209]
##### Timeseries version

0.4.0

##### Orange version

3.32 
also tried with 3.31.1 and 3.30 with the same result;
same on different machines, with Win10 and Win11

##### Expected behavior
ARIMA and VAR Blocks showing their editing dialog

##### Actual behavior
Blocks do not open diaialog when being double clicked on the workspace

##### Steps to reproduce the behavior
Drag and drop ARIMA or VAR block onto the workspace

##### Additional info (worksheets, data, screenshots, ...)

Traceback (most recent call last):
  File "C:\Program Files\Orange\lib\site-packages\orangecanvas\scheme\widgetmanager.py", line 236, in __add_widget_for_node
    w = self.create_widget_for_node(node)
  File "C:\Program Files\Orange\lib\site-packages\orangewidget\workflow\widgetsscheme.py", line 300, in create_widget_for_node
    widget = self.create_widget_instance(node)
  File "C:\Program Files\Orange\lib\site-packages\orangewidget\workflow\widgetsscheme.py", line 413, in create_widget_instance
    widget.__init__()
  File "C:\Program Files\Orange\lib\site-packages\orangecontrib\timeseries\widgets\owarimamodel.py", line 29, in __init__
    super().__init__()
  File "C:\Program Files\Orange\lib\site-packages\orangecontrib\timeseries\widgets\_owmodel.py", line 47, in __init__
    self.setup_layout()
  File "C:\Program Files\Orange\lib\site-packages\orangecontrib\timeseries\widgets\_owmodel.py", line 132, in setup_layout
    self.add_main_layout()
  File "C:\Program Files\Orange\lib\site-packages\orangecontrib\timeseries\widgets\owarimamodel.py", line 43, in add_main_layout
    gui.spin(None, self, 'p', 0, 100, **kwargs))
  File "C:\Program Files\Orange\lib\site-packages\orangewidget\gui.py", line 783, in spin
    sbox = bi.control = b.control = \
AttributeError: 'NoneType' object has no attribute 'control

**Comment by janezd** [comment]
Thanks for reporting this. We noticed the problem, fixed it (in #207) and will probably release a minor revision of the add-on by tomorrow.

**Comment by dwolf33** [comment]
perfect! Thanks a lot for the quick response.
