### ISSUE TITLE
Line Chart unusable

### ISSUE THREAD

**Issue by trenkert** [biolab/orange3-timeseries#215]
##### Timeseries version 
0.4.1

##### Orange version
3.32.0

##### Expected behavior
In earlier versions of Orange3 and of the timeseries widget, Line Chart was completely usable. 

##### Actual behavior
Now, when I pull the Line Chart widget into the canvas, it simply gives an error and remains unusable.
![image](https://user-images.githubusercontent.com/143727/176874379-59b16aa4-51cc-415f-98ad-f12428776937.png)

##### Steps to reproduce the behavior
Pull in the widget and wait for a couple of seconds. 

##### Additional info (worksheets, data, screenshots, ...)

```
Traceback (most recent call last):

  File "/home/paul/Projekte/dataspell/lib/python3.10/site-packages/orangecanvas/scheme/widgetmanager.py", line 236, in __add_widget_for_node
    w = self.create_widget_for_node(node)
  
File "/home/paul/Projekte/dataspell/lib/python3.10/site-packages/orangewidget/workflow/widgetsscheme.py", line 300, in create_widget_for_node
    widget = self.create_widget_instance(node)
  
File "/home/paul/Projekte/dataspell/lib/python3.10/site-packages/orangewidget/workflow/widgetsscheme.py", line 413, in create_widget_instance
    widget.__init__()
  
File "/home/paul/Projekte/dataspell/lib/python3.10/site-packages/orangecontrib/timeseries/widgets/owlinechart.py", line 487, in __init__
    highstock.chart(
  
File "/home/paul/Projekte/dataspell/lib/python3.10/site-packages/orangecontrib/timeseries/widgets/highcharts/highcharts.py", line 234, in chart
    self.exposeObject('pydata', options)
  
File "/home/paul/Projekte/dataspell/lib/python3.10/site-packages/orangecontrib/timeseries/widgets/highcharts/highcharts.py", line 207, in exposeObject
    super().exposeObject(name, obj)
  
File "/home/paul/Projekte/dataspell/lib/python3.10/site-packages/orangewidget/utils/webview.py", line 591, in exposeObject
    self._jsobject_channel.send_object(name, obj)
  
File "/home/paul/Projekte/dataspell/lib/python3.10/site-packages/orangewidget/utils/webview.py", line 537, in send_object
    wait(until=lambda: self.receivers(self.objectChanged), timeout=30000)
  
File "/home/paul/Projekte/dataspell/lib/python3.10/site-packages/orangewidget/utils/webview.py", line 419, in wait
    raise TimeoutError()

TimeoutError
```

![image](https://user-images.githubusercontent.com/143727/176875735-fbecf902-8d4f-4326-b687-f8933e2fdf94.png)

**Comment by janezd** [comment]
Instability is caused by connection between Orange and highcharts through QWebKit. We are aware of the problem and complete reimplementation of the widget is already underway.

The problem is an old one, and the current version shouldn't have made it any worse than it was.

@PrimozGodec, @markotoplak, is there any simple and ordinary-user-friendly way to downgrade an add-on, so he Paul can check whether this would indeed help?
