### ISSUE TITLE
New version 0.5.0 gives error when using line chart

### ISSUE THREAD

**Issue by dekosan** [biolab/orange3-timeseries#230]
##### Orange version

3.32.0

##### Expected behavior
No error...

##### Actual behavior
Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecanvas/scheme/widgetmanager.py", line 372, in __process_init_queue
    self.ensure_created(node)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecanvas/scheme/widgetmanager.py", line 320, in ensure_created
    self.__add_widget_for_node(node)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecanvas/scheme/widgetmanager.py", line 236, in __add_widget_for_node
    w = self.create_widget_for_node(node)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangewidget/workflow/widgetsscheme.py", line 300, in create_widget_for_node
    widget = self.create_widget_instance(node)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangewidget/workflow/widgetsscheme.py", line 413, in create_widget_instance
    widget.__init__()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/timeseries/widgets/owlinechart.py", line 630, in __init__
    self._add_editor({})
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/timeseries/widgets/owlinechart.py", line 737, in _add_editor
    self._graph.add_plot()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/timeseries/widgets/owlinechart.py", line 473, in add_plot
    plot = LineChartPlotItem()
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/timeseries/widgets/owlinechart.py", line 206, in __init__
    super().__init__(viewBox=pg.ViewBox(defaultPadding=0.01),
TypeError: __init__() got an unexpected keyword argument 'defaultPadding'

##### Steps to reproduce the behavior
just drag on the workflow

##### Additional info (worksheets, data, screenshots, ...)
Problem occurs in Mac High Sierra and Catalina
NO problem in Windows10

Thanks for solving this issue

**Comment by ajdapretnar** [comment]
@VesnaT Was this not solved by pinning the Orange version to >=3.32.0?

**Comment by VesnaT** [comment]
> @VesnaT Was this not solved by pinning the Orange version to >=3.32.0?

No. It looks like the pyqtgraph version is too old.. I should put that into the requirements as well.

**Comment by ajdapretnar** [comment]
It seems like pyqtgraph was not updated, it's still `0.11.1`. However, Orange requirements set it to `pyqtgraph>=0.12.2`. The change seems to be implemented before the last release. So... does that mean pyqtgraph is not automatically updated with Orange? 🤔

**Comment by VesnaT** [comment]
Orange sets pyqtgraph>=0.12.2 only on master.
