### ISSUE TITLE
Moving Transform: fails internally on sparse

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-timeseries#276]
##### Timeseries version

0.6.2

##### Orange version

3.37.0.dev

##### Expected behavior
Moving Transform either:
- issues an Error (can't transform sparse)
or
- works on sparse

##### Actual behavior
Moving Transform silently fails.

##### Steps to reproduce the behavior
Corpus - Bag of Words - Form Timeseries (sequence) - Moving Transform

**Comment by ajdapretnar** [comment]
Potentially, also Form Timeseries fails on sparse. Investigate.

**Comment by ajdapretnar** [comment]
Yet another issue. This happens after introducing Select Columns between BoW and Form TS, which outputs DENSE X.

```
TypeError: float() argument must be a string or a real number, not 'csr_matrix'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ajda/miniconda3/envs/o3/lib/python3.11/site-packages/orangecanvas/scheme/signalmanager.py", line 1180, in __process_next
    if self.__process_next_helper(use_max_active=True):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ajda/miniconda3/envs/o3/lib/python3.11/site-packages/orangecanvas/scheme/signalmanager.py", line 1218, in __process_next_helper
    self.process_node(selected_node)
  File "/Users/ajda/miniconda3/envs/o3/lib/python3.11/site-packages/orangecanvas/scheme/signalmanager.py", line 846, in process_node
    self.send_to_node(node, signals_in)
  File "/Users/ajda/orange/orange-widget-base/orangewidget/workflow/widgetsscheme.py", line 806, in send_to_node
    self.process_signals_for_widget(node, widget, signals)
  File "/Users/ajda/orange/orange-widget-base/orangewidget/workflow/widgetsscheme.py", line 820, in process_signals_for_widget
    process_signals_for_widget(widget, signals, workflow)
  File "/Users/ajda/miniconda3/envs/o3/lib/python3.11/functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ajda/orange/orange-widget-base/orangewidget/workflow/widgetsscheme.py", line 923, in process_signals_for_widget
    process_signal_input(input_meta, widget, signal, workflow)
  File "/Users/ajda/miniconda3/envs/o3/lib/python3.11/functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ajda/orange/orange-widget-base/orangewidget/workflow/widgetsscheme.py", line 886, in process_signal_input_default
    notify_input_helper(
  File "/Users/ajda/miniconda3/envs/o3/lib/python3.11/functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ajda/orange/orange-widget-base/orangewidget/utils/signals.py", line 735, in set_input_helper
    handler(*args)
  File "/Users/ajda/orange/orange-widget-base/orangewidget/utils/signals.py", line 208, in summarize_wrapper
    method(widget, value)
  File "/Users/ajda/orange/orange3-timeseries/orangecontrib/timeseries/widgets/owmovingtransform.py", line 362, in set_data
    self.commit.now()
  File "/Users/ajda/orange/orange-widget-base/orangewidget/gui.py", line 2014, in do_commit
    commit.call()
  File "/Users/ajda/orange/orange-widget-base/orangewidget/gui.py", line 1879, in call
    acting_func(instance)
  File "/Users/ajda/orange/orange3-timeseries/orangecontrib/timeseries/widgets/owmovingtransform.py", line 375, in commit
    ts = [self._compute_sliding_window,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ajda/orange/orange3-timeseries/orangecontrib/timeseries/widgets/owmovingtransform.py", line 441, in _compute_sliding_window
    return Timeseries.from_numpy(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ajda/orange/orange3-timeseries/orangecontrib/timeseries/timeseries.py", line 175, in from_numpy
    table = Table.from_numpy(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ajda/orange/orange3/Orange/data/table.py", line 919, in from_numpy
    X, Y, W = _check_arrays(X, Y, W, dtype='float64')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ajda/orange/orange3/Orange/data/table.py", line 2455, in _check_arrays
    array = np.asarray(array, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence.
```
