### ISSUE TITLE
Error while importing 'orangecontrib.timeseries.widgets.owyahoofinance'. The widget will not be shown.

### ISSUE THREAD

**Issue by yurivict** [biolab/orange3-timeseries#57]
```
$ orange-canvas 
Error while importing 'orangecontrib.timeseries.widgets.owyahoofinance'. The widget will not be shown.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/Orange/canvas/registry/discovery.py", line 261, in iter_widget_descriptions
    module = asmodule(name)
  File "/usr/local/lib/python3.6/site-packages/Orange/canvas/registry/discovery.py", line 491, in asmodule
    return __import__(module, fromlist=[""])
  File "/usr/local/lib/python3.6/site-packages/orangecontrib/timeseries/widgets/owyahoofinance.py", line 10, in <module>
    from orangecontrib.timeseries.datasources import finance_data
  File "/usr/local/lib/python3.6/site-packages/orangecontrib/timeseries/datasources.py", line 4, in <module>
    import pandas_datareader.data as web
  File "/usr/local/lib/python3.6/site-packages/pandas_datareader/__init__.py", line 2, in <module>
    from .data import (DataReader, Options, get_components_yahoo,
  File "/usr/local/lib/python3.6/site-packages/pandas_datareader/data.py", line 14, in <module>
    from pandas_datareader.fred import FredReader
  File "/usr/local/lib/python3.6/site-packages/pandas_datareader/fred.py", line 1, in <module>
    from pandas.core.common import is_list_like
ImportError: cannot import name 'is_list_like'
```

orange3-3.13.0.120
py36-orange3-timeseries-0.3.3
py36-pandas-0.23.0
py36-pandas-datareader-0.6.0_1

**Comment by kernc** [comment]
Upstream bug: https://github.com/pydata/pandas-datareader/issues/534. For now, [installing the dev version](https://pandas-datareader.readthedocs.io/en/latest/#install-latest-development-version) is recommended.
