### ISSUE TITLE
ImportError: cannot import name 'is_list_like'

### ISSUE THREAD

**Issue by brylie** [biolab/orange3-timeseries#59]
*Timeseries version:* 0.33

*Orange version:* 3.16.0

# Expected behavior
Orange3 should start without error when timeseries plugin is enabled.

# Actual behavior
When starting Orange3 with the timeseries plugin enabled, the following error occurs:

```py
Error while importing 'orangecontrib.timeseries.widgets.owyahoofinance'. The widget will not be shown.
Traceback (most recent call last):
File ".../lib/python3.6/site-packages/Orange/canvas/registry/discovery.py", line 261, in iter_widget_descriptions
module = asmodule(name)
File ".../lib/python3.6/site-packages/Orange/canvas/registry/discovery.py", line 491, in asmodule
return __import__(module, fromlist=[""])
File ".../lib/python3.6/site-packages/orangecontrib/timeseries/widgets/owyahoofinance.py", line 10, in 
from orangecontrib.timeseries.datasources import finance_data
File ".../lib/python3.6/site-packages/orangecontrib/timeseries/datasources.py", line 4, in 
import pandas_datareader.data as web
File ".../lib/python3.6/site-packages/pandas_datareader/__init__.py", line 2, in 
from .data import (DataReader, Options, get_components_yahoo,
File ".../lib/python3.6/site-packages/pandas_datareader/data.py", line 14, in 
from pandas_datareader.fred import FredReader
File ".../lib/python3.6/site-packages/pandas_datareader/fred.py", line 1, in 
from pandas.core.common import is_list_like
ImportError: cannot import name 'is_list_like'
```

# Steps to reproduce the behavior
1) install the latest version of pandas
2) install the latest version of Orange3
3) install the timeseries plugin
4) restart Orange3

**Comment by brylie** [comment]
Looks like this issue was fixed upstream:
https://github.com/pydata/pandas-datareader/pull/520

**Comment by ajdapretnar** [comment]
Yes, you need to update pandas_datareader. They were moving some things around and caused this.

**Comment by brylie** [comment]
Ok, thanks. I will try from scratch today. I think I am having environment issues, where some global pip packages are being used from my conda environment... TBC ☺
