### ISSUE TITLE
Line Chart Widget is missing in Timeseries

### ISSUE THREAD

**Issue by CornelisRemmert** [biolab/orange3-timeseries#7]
The Line Chart Widget seems to be missing in the Timeseries add-on

![image](https://cloud.githubusercontent.com/assets/20670746/21687870/2b7f6866-d36b-11e6-8967-c72a7aa5b0e9.png)

**Comment by kernc** [comment]
Can you share the output that appears if you run `python -m Orange.canvas -l 4` in cmd, i.e.:
```sh
C:\Python34\> python.exe -m Orange.canvas -l 4
```

**Comment by kernc** [comment]
The problem is these lines:
```text
Error while importing 'orangecontrib.timeseries.widgets.owlinechart'.
Traceback (most recent call last):
  File "C:\Users\datazin\Anaconda3\envs\Orange3\lib\site-packages\Orange\canvas\registry\discovery.py", line 261, in iter_widget_descriptions
    module = asmodule(name)
  File "C:\Users\datazin\Anaconda3\envs\Orange3\lib\site-packages\Orange\canvas\registry\discovery.py", line 493, in asmodule
    return __import__(module, fromlist=[""])
  File "C:\Users\datazin\Anaconda3\envs\Orange3\lib\site-packages\orangecontrib\timeseries\widgets\owlinechart.py", line 19, in <module>
    class PlotConfigWidget(QWidget, widget.OWComponent):
AttributeError: module 'Orange.widgets.widget' has no attribute 'OWComponent'
```
`OWComponent` was moved to _widget.py_ only recently. You can consider updating Orange (preferred; many bugs fixed, new introduced), or wait until tomorrow and just update the add-on from PyPI or install it from git:
```bash
pip install git+https://github.com/biolab/orange3-timeseries.git
```
